name: Static Analysis

on: [ push, pull_request ]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/composer/files
          key: php-8.3-composer-${{ hashFiles('**/composer.json') }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - run: |
          composer require --dev --ignore-platform-req=ext-oci8 yajra/laravel-oci8
          composer update --no-interaction --no-progress --prefer-dist --ignore-platform-req=ext-oci8
      - run: vendor/bin/phpstan analyse --error-format=github
